/**
 * @fileoverview
 * JSDoc type definitions for the Killer Control subscription model.
 * Used for IDE intellisense and documentation — no TypeScript required.
 */

/**
 * A single price history entry.
 * @typedef {Object} PriceHistoryEntry
 * @property {string} date     - ISO date string "2024-03-01"
 * @property {number} amount   - Price at that date (e.g. 12.99)
 * @property {string} [reason] - Optional label: "Actualización de plan", "Subida anual", etc.
 */

/**
 * A cheaper alternative service.
 * @typedef {Object} Alternative
 * @property {string} name           - Service name (e.g. "Disney+")
 * @property {number} price          - Monthly price (e.g. 8.99)
 * @property {string} url            - Landing URL (e.g. "disneyplus.com")
 * @property {string} planEquivalent - What the plan includes (e.g. "4K, 4 perfiles")
 * @property {number} savings        - Calculated monthly saving vs current sub
 * @property {number} [annualSavings]- Calculated annual saving
 * @property {string} [note]         - Optional note (e.g. "Incluye Star+")
 */

/**
 * The analysis block attached to a subscription.
 * @typedef {Object} AnalysisBlock
 * @property {number}        priceIncreaseThreshold - % minimum to flag a "relevant" price rise (e.g. 5)
 * @property {string}        [priceIncreaseSince]   - ISO date of detected price increase
 * @property {number}        [priceIncreasePercent] - Calculated % increase
 * @property {Alternative[]} alternatives           - Cheaper alternatives list
 * @property {1|2|3|4|5}    usageScore             - How much the user uses the service (1=little, 5=a lot)
 * @property {number}        [valueScore]           - Calculated: usageScore / pricePerMonth * 10
 */

/**
 * Optional promotional pricing applied to the subscription.
 * @typedef {Object} PromoBlock
 * @property {number} promoPrice   - Discounted price during promo
 * @property {number} regularPrice - Price after promo ends
 * @property {string} promoEndDate - ISO date when promo expires
 */

/**
 * A severity-graded alert generated by analyzeSubscription().
 * @typedef {Object} SubscriptionAlert
 * @property {'price_increase'|'promo_ending'|'low_usage'} type
 * @property {string}            message
 * @property {'low'|'medium'|'high'} severity
 */

/**
 * Full result returned by analyzeSubscription().
 * @typedef {Object} SubscriptionAnalysis
 * @property {boolean}               hasPriceIncrease
 * @property {number}                priceIncreasePercent
 * @property {string|undefined}      priceIncreaseSince
 * @property {Alternative[]}         alternatives        - Filtered & sorted by savings desc
 * @property {boolean}               promoAlert
 * @property {number}                daysUntilPromoEnd   - Infinity if no promo
 * @property {number}                valueScore
 * @property {SubscriptionAlert|undefined} alert         - Most relevant alert (or undefined)
 */

/**
 * The main Subscription model.
 * @typedef {Object} Subscription
 * @property {string}            id
 * @property {string}            name
 * @property {number}            amount          - Current monthly amount
 * @property {string}            [category]
 * @property {string}            [renewalDate]   - ISO date of next renewal
 * @property {string}            [website]
 * @property {PriceHistoryEntry[]} [priceHistory]
 * @property {AnalysisBlock}     [analysis]
 * @property {PromoBlock}        [promo]
 */

// Export empty object so this file can be imported (keeps bundlers happy)
export {};
